// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:safe_guard/firebase_options.dart';
import 'package:flutter/material.dart';
import 'package:safe_guard/main.dart';


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAustp2DLHF8Nbw1ynk2M4JmBLXvORJEo4',
    appId: '1:279985915704:web:4f97e20cdfcef9edeba3cd',
    messagingSenderId: '279985915704',
    projectId: 'safeguard-efb3a',
    authDomain: 'safeguard-efb3a.firebaseapp.com',
    storageBucket: 'safeguard-efb3a.appspot.com',
    measurementId: 'G-XQHV8SMSJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3kdiLFkRm_BZHzi-oGT7cJTahN5KDrNA',
    appId: '1:279985915704:android:4122b724cea8a48eeba3cd',
    messagingSenderId: '279985915704',
    projectId: 'safeguard-efb3a',
    storageBucket: 'safeguard-efb3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSWT3mw5jS60J3eFmUoINO-KbJHDSmppI',
    appId: '1:279985915704:ios:bdb06bc3301d8d89eba3cd',
    messagingSenderId: '279985915704',
    projectId: 'safeguard-efb3a',
    storageBucket: 'safeguard-efb3a.appspot.com',
    iosBundleId: 'com.example.safeGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSWT3mw5jS60J3eFmUoINO-KbJHDSmppI',
    appId: '1:279985915704:ios:3d05bed24d396ca5eba3cd',
    messagingSenderId: '279985915704',
    projectId: 'safeguard-efb3a',
    storageBucket: 'safeguard-efb3a.appspot.com',
    iosBundleId: 'com.example.safeGuard.RunnerTests',
  );
}
